service: weather
provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: eu-central-1

functions:
  main:
    handler: handler.main
    events:
          - http:
              path: weather
              method: post