vesion: 2
jobs:
  server:
    docker:
      - image: myshenin/thesis:0.3
    steps:
      - checkout
      - run: cd server/test && npm install
      - run: cd server/src/t-sne && \
              sls deploy --stage dev && \
              npm run test:tsne && \
              sls deploy --stage prod

workflows:
  version: 2
  integration:
    jobs:
      - server
deployment:
  staging:
    branch: master
    codedeploy:
      myshenin.thesis:
        deployment_group: my-deployment-group
