vesion: 2
jobs:
  server:
    docker:
      - image: myshenin/thesis:0.0
    steps:
      - checkout
      - run: cd server/test && npm install
      - run: cd server/src/t-sne &&
             npm install &&
             sls deploy --stage dev &&
             cd ../../test && 
             npm run test:tsne &&
             cd ../src/t-sne &&
             sls deploy --stage prod
      - run: cd server/src/weather && npm install && sls deploy --stage dev && cd ../../test && npm run test:weather && cd ../src/weather && sls deploy --stage prod
      - run: cd server/src/result && npm install && sls deploy --stage dev && cd ../../test && npm run test:result && cd ../src/result && sls deploy --stage prod
  client:
    docker:
      - image: myshenin/thesis:0.0
    steps:
      - checkout
      - run: cd client && npm install
workflows:
  version: 2
  integration:
    jobs:
      - server
      - client
deployment:
  staging:
    branch: master
    codedeploy:
      myshenin.thesis:
        deployment_group: my-deployment-group
