vesion: 2
jobs:
  server:
    docker:
      - image: myshenin/thesis:0.3
    steps:
      - checkout
      - run: ls -a
      - run: cd thesis/server/test && npm install
      - run: npm run test

workflows:
  check:
    jobs:
      - server

